### PR TITLE
Feature add created date

### PR DESCRIPTION
**Pull request by riggaroo**
Hi @lgleasain 
I have tried to add a created date to each book. Storing it in the Database as an int as firebase doesn't allow date objects. 
I have managed to get the datepicker to bind two ways with the editing of a book date, but I am having an issue with the "add" functionality as it doesn't call the setter on the add.ts function. 
Its the same code so I am not sure why it would do that. I am thinking that maybe because that form is added dynamically to the view that the binding doesn't work? I dunno - have spent a few hours. 

Would you be able to assist with debugging this issue? This pull request contains the changes for the created date.

### CODE REVIEW

**Comment by lgleasain** [comment]
Ok,  the issue is related to the book enabled checkbox.  We will need to dig in to this further,  but the short term fix is to click the book enabled checkbox.  If you don't want it enabled toggle it again and then things will work.  We will need to get support for this new field added in for edit for this to be ready to go but add looks like it is working correctly with that workaround.  It looks like that is partially added,  but something is jacked up when trying to save.  Will dig into that.

**Comment by riggaroo** [comment]
Hi Lance,
Thanks for taking a look.
I have implemented "editing a date" when the book is already created.
With regards to the bug on adding a book, I have had a look at the checkbox enabled but I am not sure I understand your suggestion. Would you mind elaborating?

**Comment by lgleasain** [comment]
Hey,

With edit,  it looks like it is working.....not sure why I saw a error with this before......strange.  

With the add book,  there is a checkbox called "Book Enabled" under the "book URL" field.  This is the source of the error.  I was getting a null object error with this.  The temporary workaround is to check the box to enable it.  If you don't want to add it as enabled you can then check it again to disable it and things will save.  There is a object binding/creation issue with this,  but it was there before you added any of your changes.

**Comment by lgleasain** [comment]
Ok,  I just added a fix for this checkbox issue.  Things should now work correctly without this workaround.

**Comment by riggaroo** [comment]
Hi Lance, 
So the problem of the date picker isn't fixed with this. When you add a book, no matter the date you select on the picker, the item always saves with today's date. 
It seems like the datepicker doesn't trigger displayDateAdd() setter method. 

What is weird is that the edit date function is able to edit the date which is using very similar code.

**Comment by lgleasain** [comment]
oooohhhh,  I didn't realize that was the issue.  Lemme dig a little bit more then.

**Comment by lgleasain** [comment]
Found it and merged it in.....it was a very small syntax issue...you had ng-model,  but it needed to be ngModel .  Took me a bit to find it and definitely something that his easy to miss.

**Comment by riggaroo** [comment]
Agh! Sneaky bug I couldn't find it 😢 thanks for finding it!

**Pull request merged**
